apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway  
  template:
    metadata:
      labels:
        app: gateway 
    spec:
      containers:
      - name: gateway
        image: leonardosartorello/java-gateway-k8s:v1
        ports:
        - containerPort: 80
        env:
        - name: SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pagamentos  
  template:
    metadata:
      labels:
        app: pagamentos 
    spec:
      containers:
      - name: pagamentos
        image: leonardosartorello/java-pagamentos-k8s:v1
        ports:
        - containerPort: 80
        env:
        - name: SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: DB_HOST

        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: senhas
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pedidos  
  template:
    metadata:
      labels:
        app: pedidos 
    spec:
      containers:
      - name: pedidos
        image: leonardosartorello/java-pedidos-k8s:v1
        ports:
        - containerPort: 80
        env:
        - name: SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: DB_HOST  
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: senhas
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server  
  template:
    metadata:
      labels:
        app: server 
    spec:
      containers:
      - name: server
        image: leonardosartorello/java-server-k8s:v1
        ports:
        - containerPort: 80
        env:
        - name: SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: dados
              key: DB_HOST  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD